In [2]:
import numpy as np


In [3]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [3]:
#print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [4]:
#print y 

[[0]
 [1]
 [1]
 [0]]


In [7]:
#Step 2 build model

num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [6]:
#print syn0

[[-0.00896954  0.63051633  0.97238696  0.2205912 ]
 [ 0.80236435 -0.88821416  0.71289103  0.52543106]
 [ 0.27429976 -0.29205953  0.57121292  0.69364235]]


In [7]:
#print syn1

[[ 0.30339426]
 [-0.45778467]
 [ 0.09523754]
 [-0.34639674]]


In [5]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [8]:
#Step 3 Train Model

for j in xrange(num_epochs):
    #feed forward through layers 0,1, and 2
    k0 = x
    k1 = nonlin(np.dot(k0, syn0))
    #print "k1 and weight multiplication "
    #print k0, syn0
    #print "input layer  k "
    #print k1
    k2 = nonlin(np.dot(k1, syn1))
    #print "syn1"
    #print syn1
    #print "input layer k2"
    #print k2
    #how much did we miss the target value?
    k2_error = y - k2
    
    #print "actual output"
    #print y
    #print "code output"
    #print k2
    #print "error in praposgation "
    #print k2_error   
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(k2_error)))
        print "output:" +str(k2)
        print "actual out:"+str(y)
    #in what direction is the target value?
    k2_delta = k2_error*nonlin(k2, deriv=True)
    #print "k2_delta in error field"
    #print k2
    #print "dervatinve of k2"
    #print nonlin(k2, deriv=True)
    #print "k2 delta is k2.deriavtiver of k2"
    #print k2_delta    
    #how much did each k1 value contribute to k2 error
    k1_error = k2_delta.dot(syn1.T)
    #print "k1_error"
    #print k1    
    k1_delta= k1_error * nonlin(k1,deriv=True)    
    syn1 =syn1+ k1.T.dot(k2_delta)
    syn0 =syn0+ k0.T.dot(k1_delta)
    

Error:0.496016430021
output:[[ 0.44474967]
 [ 0.48246255]
 [ 0.37089006]
 [ 0.39266866]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00836997876717
output:[[ 0.00878384]
 [ 0.99134682]
 [ 0.99143247]
 [ 0.00747537]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.0057386598609
output:[[ 0.00602576]
 [ 0.99406575]
 [ 0.9941526 ]
 [ 0.00514723]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00462199541832
output:[[ 0.00485537]
 [ 0.99522133]
 [ 0.99530045]
 [ 0.00415439]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00396962751925
output:[[ 0.00417149]
 [ 0.99589675]
 [ 0.9959691 ]
 [ 0.00357288]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00352998519336
output:[[ 0.00371051]
 [ 0.99635201]
 [ 0.99641888]
 [ 0.00318031]]
actual out:[[0]
 [1]
 [1]
 [0]]
